version: "3"

services:
  rosbag2dataset:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/root/rosbag2dataset
      - ~/dataset/bottle_grasp_2ext:/root/bagfiles
      - ~/dataset/bottle_grasp_2ext/converted:/root/dataset

      # test
      # - ./testbagfiles:/root/bagfiles
      # - ./testdataset:/root/dataset
    stdin_open: true
    privileged: true
